Case/urls.py
from django.urls import path

from . import views

app_name = 'case' 
urlpatterns = [
    path('', views.cases, name='case'),
]

Runs/urls.py
from django.urls import path

from . import views

app_name = 'runs' 
urlpatterns = [
    path('', views.runs, name='runs'),
]

Team/urls.py
from django.urls import path

from . import views

app_name = 'team' 
urlpatterns = [
    path('', views.teams, name='teams'),
]

Tests/urls.py
from django.urls import path

from . import views

app_name = 'tests' 
urlpatterns = [
    path('', views.tests, name='tests'),
]

Users/urls.py
from django.urls import path, re_path

from . import views

app_name = 'users'

urlpatterns = [
    # re_path(r'^register/$', views.register, name='register'),
    path('', views.login_page, name='login_page'),
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    re_path(r'^user/(?P<pk>\d+)/profile/$', views.profile, name='profile'),
    # re_path(r'^user/(?P<pk>\d+)/profile/update/$', views.profile_update, name='profile_update'),
    # re_path(r'^user/(?P<pk>\d+)/pwd_change/$', views.pwd_change, name='pwd_change'),
    # re_path(r"^logout/$", views.logout, name='logout'),
]

Case/models.py
from django.db import models

# Create your models here.

Runs/models.py
from django.db import models

# Create your models here.

Team/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Note(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField()
    def __str__(self):
        return self.title

Tests/models.py
from django.db import models

# Create your models here.

Case/views.py
from django.shortcuts import render


# Create your views here.
# @app.route('/case')
# @jwt_required(optional=False)
def cases(request):  # put application's code here
    # current_user = get_jwt_identity()
    # print(current_user)
    return render(request, 'cases.html')

Runs/views.py
from django.shortcuts import render


# Create your views here.
# @app.route('/runs')
# @jwt_required(optional=False)
def runs(request):  # put application's code here
    # current_user = get_jwt_identity()
    # print(current_user)
    return render(request, 'runs.html')

Team/views.py
from unicodedata import name

from django.contrib.auth.decorators import login_required
from django.shortcuts import render


@login_required
def teams(request):  # put application's code here
    # current_user = get_jwt_identity()
    # print(current_user)
    return render(request, 'team.html')

Tests/views.py
from django.shortcuts import render


# Create your views here.
# @app.route('/tests')
# @jwt_required(optional=False)
def tests(request):  # put application's code here
    # current_user = get_jwt_identity()
    # print(current_user)
    return render(request, 'tests.html')

templates/fundamental.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://kendo.cdn.telerik.com/2022.1.119/styles/kendo.common.min.css" rel="stylesheet" />
    <link href="https://kendo.cdn.telerik.com/2022.1.119/styles/kendo.default.min.css" rel="stylesheet" />
    <script src="https://kendo.cdn.telerik.com/2022.1.119/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2022.1.119/js/kendo.all.min.js"></script>
</head>

{% block main %}{% endblock %}

{% block scripts %}{% endblock %}
</script>

</body>
</html>

templates/fundamental_page.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <style>
        html {
            font-size: 14px;
            font-family: Arial, Helvetica, sans-serif;
        }
    </style>
    <title>{% block title %}{% endblock %}</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://kendo.cdn.telerik.com/2022.1.119/styles/kendo.common.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2022.1.119/styles/kendo.default-main.min.css" />
    <script src="https://kendo.cdn.telerik.com/2022.1.119/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2022.1.119/js/kendo.all.min.js"></script>

    {% block style_block %}{% endblock %}
    <style type="text/css">
        .menu_text_color {
            color: white;
            text-decoration: none;
        }

        .menu_text_color:hover {
            color: #63c4c4;
            text-decoration: none;
        }

        .k-button {
            background-color: #0066aa;
            border-color: #0066aa;
        }

        .k-grid-header .k-header {
            background-color: #0066aa;
            color: white;
        }
    </style>

</head>


<body>
    <div class="appbar-container">
        <div id="appbar" style="background: #0066aa"></div>
    </div>

    <div id="window">
        <div style="width: 100%; text-align: center">
            <H2>
                Fabian Lin
            </H2>
            <p>
                fabianlin@keenlity.com
            </p>
            <H4>
                Admin
            </H4>
            <p>
                <input id="password1" type="password">
                <input id="passwordC" type="password">
            </p>

            <p>
                <input id="languages" style="width: 100%;" />
            </p>
            <p>
                <button id="saveBtn" onclick="saveSettings()"
                    style="width: 100%;background:#0066aa; border-color: #0066aa">Save</button>
            </p>
        </div>
    </div>


    <script>
        $("#appbar").kendoAppBar({
            positionMode: "sticky",
            position: "top",
            themeColor: "dark",
            items: [
                { template: '<img class="img-responsive" src="/static/img/keenlity_logo.png" style="max-height: 28px;">', type: "contentItem" },
                { width: 8, type: "spacer" },
                { template: '<a class="menu_text_color" href="\\#">Dashboard</a>', type: "contentItem" },
                { width: 8, type: "spacer" },
                { template: '<a class="menu_text_color" href="/runs">Test Runs</a>', type: "contentItem" },
                { width: 8, type: "spacer" },
                { template: '<a class="menu_text_color" href="/case">Cases</a>', type: "contentItem" },
                { width: 8, type: "spacer" },
                { template: '<a class="menu_text_color" href="/team">Team</a>', type: "contentItem" },
                { type: "spacer" },
                { template: '<span id="user_settings" style="font-weight: bold;cursor: pointer" onclick="openSetting()">fabianlin@keenlity.com</span>', type: "contentItem" },
            ]
        })

        const userSettingWindow = $("#window").kendoWindow({
            width: "300px",
            title: "User Setting",
            visible: false,
            modal: true,
            actions: [
                "Close"
            ],
        }).data("kendoWindow");

        $("#password1").kendoTextBox({
            placeholder: "Password",
        });
        $("#passwordC").kendoTextBox({
            placeholder: "Confirm",
        });

        function openSetting() {
            userSettingWindow.center().open()
        }

        function saveSettings() {
            userSettingWindow.center().close();
        }

        $(document).ready(function () {
            var data = [
                { text: "Black", value: "1" },
                { text: "Orange", value: "2" },
                { text: "Grey", value: "3" }
            ];

            // create DropDownList from input HTML element
            $("#languages").kendoDropDownList({
                dataTextField: "text",
                dataValueField: "value",
                dataSource: data,
                index: 0,
            });

            $("#saveBtn").kendoButton({
                themeColor: "primary"
            });
            const settingWindow = $("#window").parent();
            settingWindow.find('.k-window-titlebar,.k-window-actions').css('backgroundColor', '#0066ac');
            settingWindow.find('.k-window-title').css('color', '#ffffff');
            settingWindow.find('.k-window-action').css('color', '#ffffff');
        });


    </script>

    {% block main %}{% endblock %}

    {% block scripts %}{% endblock %}
    </script>

</body>

</html>

templates/index.html
{% extends "fundamental.html" %}

{% block title %}
KEENLITY CASE -- LOGIN
{% endblock %}
{# ------- #}
{% load static %}


{% block main %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<body style="background-color: #0066aa">

    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-xs-4 thumb align-center">

            </div>
            <div class="col-lg-4 col-md-4 col-xs-4 thumb align-center">
                <img class="img-responsive" src="{% static 'img/keenlity_logo.png' %}"
                    style="max-width:100%; margin-top: 300px;">

                {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}
                <div class=”alert alert-danger”>
                    <li style="color:red">{{ error|escape }}</li>
                </div>
                {% endfor %}
                {% endfor %}
                {% endif %}

                <form class="needs-validation" action="/login" method="POST" novalidate>
                    {% csrf_token %}
                    <div class="py-3" style="display: block;margin: 0 auto;width: 200px;">
                        <label class="form-label text-white fw-light">E-mail</label>
                        <input name="username" type="text" class="form-control" placeholder="Name" required>
                        <div class="invalid-feedback">
                            Please enter correct mail.
                        </div>
                    </div>
                    <div style="margin: 30px;display: block;margin: 0 auto;width: 200px;">
                        <label class="form-label text-white fw-light">Password</label>
                        <input name="password" type="password" class="form-control" placeholder="Password" required>
                        <div class="invalid-feedback">
                            Please enter password.
                        </div>
                    </div>
                    <div style="margin: 30px">
                        <input type="submit" value="Login"
                            style="display: block;margin: 0 auto;width: 200px;background:#63c4c4; border-color: #63c4c4">
                    </div>
                </form>

                <div class="row justify-content-center" style="margin-top: 100px;">
                    <a class="col-5 link-light text-decoration-none fw-bold" href="{% url 'users:register' %}">Register
                        account</a>
                </div>
            </div>
        </div>

        <script>
            // function login() {
            //     let username = $("#username").val();
            //     let password = $("#password").val();
            //     let datas = { "username": username, "password": password };
            //     $.ajax({
            //         url: '/accounts/login',
            //         data: JSON.stringify(datas),
            //         type: "POST",
            //         dataType: "json",
            //         contentType: "application/json;charset=utf-8",
            //         success: function (resultData) {
            //             const token = resultData.access_token;
            //             window.location.replace("/case");
            //         },
            //         error: function (xhr, ajaxOptions, thrownError) {
            //             console.log(xhr.status);
            //             console.log(thrownError);
            //         }
            //     });
            // }

            // $(document).ready(function () {
            //     // create TextBox from input HTML element
            //     $("#username").kendoTextBox({
            //         placeholder: "Name",
            //     });

            //     $("#password").kendoTextBox({
            //         placeholder: "Password",
            //     });

            //     $("#loginBtn").kendoButton({
            //         themeColor: "primary"
            //     });
            // });

            // Example starter JavaScript for disabling form submissions if there are invalid fields
            (function () {
                'use strict'

                // Fetch all the forms we want to apply custom Bootstrap validation styles to
                var forms = document.querySelectorAll('.needs-validation')

                // Loop over them and prevent submission
                Array.prototype.slice.call(forms)
                    .forEach(function (form) {
                        form.addEventListener('submit', function (event) {
                            if (!form.checkValidity()) {
                                event.preventDefault()
                                event.stopPropagation()
                            }

                            form.classList.add('was-validated')
                        }, false)
                    })
            })()
        </script>
        {% endblock %}
        {# ------- #}

templates/page.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Restaurant King</title>
</head>

<body>
    <h2>歡迎來到餐廳王</h2>
    {% if request.user.is_authenticated %}
    <p>{{request.user}} 您已經登入囉</p>
    <a href="/restaurants_list/">餐廳列表</a>
    {% else %}
    <p>您尚未登入喔~<a href="/accounts/login/">登入</a></p>
    {% endif %}
</body>

</html>

templates/register.html
{% extends "fundamental.html" %}

{% block title %}
KEENLITY CASE -- LOGIN
{% endblock %}
{# ------- #}
{% load static %}


{% block main %}

<body>

    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-xs-4 thumb align-center">

            </div>
            <div class="col-lg-4 col-md-4 col-xs-4 thumb align-center">
                <!-- <img class="img-responsive" src="{% static 'img/keenlity_logo.png' %}"
                    style="max-width:100%; margin-top: 300px;"> -->

                <div class="row justify-content-center" style="margin-top: 200px;text-align:center;">
                    <h1 class="display-1 fw-bold" style="color: #0066aa;">
                        KEENLITY
                    </h1>
                </div>

                {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}
                <div class=”alert alert-danger”>
                    <li style="color:red">{{ error|escape }}</li>
                </div>
                {% endfor %}
                {% endfor %}
                {% endif %}

                <form class="row g-3 needs-validation" method="POST" novalidate>
                    {% csrf_token %}
                    <div class="col-12">
                        <label class="form-label">Account Type</label>
                        <select id="account_type" name="account_type" class="form-select k-picker"
                            onchange="showTaxIdDiv(this)">
                            <option value="1" selected>Organization</option>
                            <option value="0">Personal</option>
                        </select>
                        </select>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label">Mail</label>
                        <input name="email" type="email" class="form-control form-control-sm"
                            value='{{ form_data.email }}' required>
                        <div class="invalid-feedback">
                            Please enter mail.
                        </div>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label">Name</label>
                        <input name="username" type="text" class="form-control form-control-sm"
                            value='{{ form_data.username }}' required>
                        <div class="invalid-feedback">
                            Please enter name.
                        </div>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label">Password</label>
                        <input name="password1" type="password" class="form-control form-control-sm">
                        <div class="invalid-feedback">
                            Please enter password.
                        </div>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label">Confirm Password</label>
                        <input name="password2" type="password" class="form-control form-control-sm" required>
                        <div class="invalid-feedback">
                            Please enter confirm password.
                        </div>
                    </div>
                    <div class="col-12">
                        <label class="form-label">Address</label>
                        <input name="address" type="text" class="form-control form-control-sm"
                            value='{{ form_data.address }}' required>
                        <div class="invalid-feedback">
                            Please enter address.
                        </div>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label">Phone</label>
                        <input name="phone" type="text" class="form-control form-control-sm"
                            value='{{ form_data.phone }}' required>
                        <div class="invalid-feedback">
                            Please enter phone.
                        </div>
                    </div>
                    <div class="col-md-6">
                        <label id="tax_id_label" class="form-label">Tax ID</label>
                        <input id="tax_id_input" name="tax_id" type="text" class="form-control form-control-sm"
                            value='{{ form_data.tax_id }}' required>
                        <div class="invalid-feedback">
                            Please enter tax id.
                        </div>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label">Tester</label>
                        <select name="tester" class="form-select k-picker">
                            {% for i in range %}
                            <option value="{{ i }}">{{ i }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label">Viewer</label>
                        <select name="viewer" class="form-select k-picker">
                            {% for i in range %}
                            <option value="{{ i }}">{{ i }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-12">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="" id="invalidCheck2" required>
                            <label class="form-check-label" for="invalidCheck2">
                                User Terms and Privacy Policy
                            </label>
                        </div>
                    </div>
                    <div class="col-12 py-4">
                        <input type="submit" value="Register"
                            style="display: block;margin: 0 auto;width: 200px;background:#63c4c4; border-color: #63c4c4">
                    </div>
                </form>

                <div class="row justify-content-center">
                    <a class="col-8 mb-5 link-dark text-decoration-none fw-bold"
                        href="{% url 'users:login_page' %}">Already
                        have account? Login Now
                    </a>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    // Account Type 關於是否顯示 Tax ID
    function showTaxIdDiv(select) {
        if (select.value == 1) {
            document.getElementById('tax_id_label').style.display = "block";
            document.getElementById('tax_id_input').style.display = "block";
            document.getElementById('tax_id_input').setAttribute('required', '');
        } else {
            document.getElementById('tax_id_label').style.display = "none";
            document.getElementById('tax_id_input').style.display = "none";
            document.getElementById('tax_id_input').removeAttribute('required');
        }
    }

    (function () {
        'use strict'

        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        var forms = document.querySelectorAll('.needs-validation')

        // Loop over them and prevent submission
        Array.prototype.slice.call(forms)
            .forEach(function (form) {
                form.addEventListener('submit', function (event) {
                    if (!form.checkValidity()) {
                        event.preventDefault()
                        event.stopPropagation()
                    }

                    form.classList.add('was-validated')
                }, false)
            })
    })()
</script>
{% endblock %}

templates/runs.html
{% extends "fundamental_page.html" %}



{% block title %}
    KEENLITY CASE
{% endblock %}
{# -------  #}

{% block style_block %}
    <style>
        #miniDashboard{
            margin-top: 16px;
            border: 1px solid #0066aa;
        }
    </style>

{% endblock %}


{% block main %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-8">
                <div id="miniDashboard">
                    <div class="row">
                        <div class="col-lg-3">
                            <div style="padding: 8px;">
                                <input id="runsSelector" style="width: 100%">
                            </div>

                            <div style="text-align: center">
                                <div style="color: #555555">100 / 500</div>
                                <div style="color: #555555">20%</div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div id="runChart"></div>

                        </div>
                        <div class="col-lg-5">

                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-4">
                2222222222    2222222222    2222222222    2222222222    2222222222    2222222222    2222222222    2222222222    2222222222    2222222222    2222222222    2222222222
            </div>
        </div>

    </div>


    <script>

        $("#runsSelector").kendoDropDownList({
            dataTextField: "role_name",
            dataValueField: "role_value",
            dataSource: {
                transport: {
                    read: {
                        url: "/roles",
                        type: "get",
                        dataType: "json",
                    },

                }
            }
        });

        $("#runChart").kendoChart({
                title: {
                    text: "What is you favourite sport?"
                },
                legend: {
                    position: "top"
                },
                seriesDefaults: {
                    labels: {
                        template: "#= category # - #= kendo.format('{0:P}', percentage)#",
                        position: "outsideEnd",
                        visible: true,
                        background: "transparent"
                    }
                },
                seriesColors: ["#4C9486", "#E86F5E", "#FFD266", "#E6321B", "#8A8F84", "#D86B00", "#F47787"],
                series: [{
                    type: "pie",
                    colorField: "valueColor",
                    labels: {
                      visible: true,
                      template: "#: value #",
                    },
                    data: [{
                        category: "Pass",
                        value: 162,
                        valueColor: "#00A600"
                    }, {
                        category: "Failed",
                        value: 85,
                        valueColor: "#FF2D2D"
                    }, {
                        category: "Retest",
                        value: 3,
                        valueColor: "#EAC100"
                    }, {
                        category: "Block",
                        value: 9,
                        valueColor: "#000000"
                    }, {
                        category: "Deprecate",
                        value: 1,
                        valueColor: "#6A6AFF"
                    }, {
                        category: "Untest",
                        value: 123,
                        valueColor: "#ADADAD"
                    }]
                }],
                tooltip: {
                    visible: true,
                    template: "#= category # - #= kendo.format('{0:P}', percentage) #"
                }
            });

    </script>


{% endblock %}
{# -------  #}